```{r}
#importing data
data = read.csv("tempo.csv", sep = ";", na.strings = "", stringsAsFactors = T)
head(data)
summary(data)
```
Exploring categorical data
```{r}
#Aparencia
counts = table(data$Aparencia)
barplot(counts, main="Aparencia", xlab = "Aparecia")
```
```{r}
counts = table(data$Vento)
barplot(counts, main ="Vento", xlab = "Vento")
```
```{r}
#Jogar
counts = table(data$Jogar)
barplot(counts, main="Jogar", xlab="Jogar")
```
Exploring numerical data
```{r}
#Temperatura
summary(data$Temperatura)
boxplot(data$Temperatura)
hist(data$Temperatura)
```

```{r}
#Umidade
summary(data$Umidade)
boxplot(data$Umidade)
hist(data$Umidade)
```
Missing Values - NAS
```{r}
#NAS
data[!complete.cases(data),]
```
Umidade out of domain
```{r}
summary(data$Umidade)
median(data$Umidade, na.rm = T)
data[is.na(data$Umidade),]$Umidade = median(data$Umidade,na.rm = T)
data[data$Umidade < 0 | data$Umidade > 100 ,]$Umidade = median(data$Umidade) 
data[data$Umidade < 0 | data$Umidade > 100 ,]
summary(data$Umidade)
data[!complete.cases(data$Umidade),]
```

Temperaturaa out of domain
```{r}
data[data$Temperatura < -130 | data$Temperatura > 130, ]$Temperatura
data[is.na(data$Temperatura),]
median(data$Temperatura, na.rm = T)
data[data$Temperatura < -130 | data$Temperatura > 130,]$Temperatura = median(data$Temperatura)
data[data$Temperatura < -130 | data$Temperatura > 130, ]
summary(data$Temperatura)
```



Aparencia out of domain
```{r}
unique(data$Aparencia)
summary(data$Aparencia)
data[!data$Aparencia %in% c("sol", "nublado", "chuva"),]$Aparencia = "chuva"
summary(data$Aparencia)
data$Aparencia = factor(data$Aparencia)
summary(data$Aparencia)
```
Checking NAs
```{r}
data[!complete.cases(data),]
summary(data)
head(data)
```
Vento NA'S
```{r}
summary(data$Vento)
data[is.na(data$Vento),]
data[is.na(data$Vento),]$Vento = 'FALSO'
data[is.na(data$Vento),]
summary(data$Vento)
summary(data)
```


